config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :students
  resources :courses
  resources :course_terms

  get 'register', to: 'enrollments#select_term'
  post 'select_course', to: 'enrollments#select_course'
  post 'select_student', to: 'enrollments#select_student'
  post 'complete_registration', to: 'enrollments#complete_registration'

  root 'visitors#index'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  validates :course_term, :student, :course, presence: true

  belongs_to :course_term
  belongs_to :student
  belongs_to :course
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def select_term
    @enrollment = Enrollment.new
    @course_terms = CourseTerm.order(year: :asc, season: :asc)
  end

  def select_course
    @enrollment = Enrollment.new
    @course_term = course_term
    @courses = Course.all
  end

  def select_student
    @enrollment = Enrollment.new
    @course_term = course_term
    @course = course
    @students = Student.all
  end

  def complete_registration
    enrollment = Enrollment.new
    enrollment.course_term = course_term
    enrollment.course = course
    enrollment.student = student
    if enrollment.save
      EnrollmentMailer.registration_email(current_account, enrollment).deliver_later if current_account.student?
      redirect_to register_path, notice: 'Course enrollment successful. Enroll another?'
    end
  end

  private

  def course_term
    CourseTerm.find(params[:enrollment][:course_term])
  end

  def course
    Course.find(params[:enrollment][:course])
  end

  def student
    Student.find(params[:enrollment][:student])
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/select_course.html.erb
<ol class="breadcrumb">
  <li><a href="<%= register_path %>">Registration</a></li>
  <li class="active"><%= @course_term %></li>
</ol>

<h2>Select a Course</h2>

<%= form_for(@enrollment, url: current_account.student? ? complete_registration_path : select_student_path, html: {class: 'form-inline'}) do |f| %>
  <div class="field form-group">
    <div class="col-sm-10">
      <%= f.collection_select(:course,
                              @courses, :id, :to_s,
                              {prompt: true, disabled: lambda { |course| !course.enrollable?(@course_term) }},
                              {class: 'form-control'}) %>
    </div>
  </div>
  <%= f.submit current_account.student? ? 'Register' : 'Next', class: 'btn btn-primary' %>
  <%= hidden_field :enrollment, :course_term, value: @course_term.id %>
  <% if current_account.student? %>
  <%= hidden_field :enrollment, :student, value: current_account.student.id %>
  <% end %>
  <div>
    <p style="font-style:italic;color:red">Note: A course cannot be selected if its enrollment capacity has been exceeded.</p>
  </div>
<% end %>

app/views/enrollments/select_student.html.erb
<ol class="breadcrumb">
  <li><a href="<%= register_path %>">Registration</a></li>
  <li><%= @course_term %></li>
  <li class="active"><%= @course %></li>
</ol>

<h2>Select a Student</h2>

<%= form_for(@enrollment, url: complete_registration_path, html: {class: 'form-inline'}) do |f| %>
  <div class="field form-group">
    <div class="col-sm-10">
      <%= f.collection_select(:student,
                              @students, :id, :to_s,
                              {prompt: true, disabled: lambda { |student| student.enrolled?(@course, @course_term) }},
                              {class: 'form-control'}) %>
    </div>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary' %>
  <%= hidden_field :enrollment, :course_term, value: @course_term.id %>
  <%= hidden_field :enrollment, :course, value: @course.id %>
  <div>
    <p style="font-style:italic;color:red">
      Note: A student cannot be selected if the student has already been enrolled in this course for this term.
    </p>
  </div>
<% end %>

app/views/enrollments/select_term.html.erb
<ol class="breadcrumb">
  <li class="active">Registration</li>
</ol>

<h2>Select a Term</h2>

<%= form_for(@enrollment, url: select_course_path, html: {class: 'form-inline'}) do |f| %>
  <div class="field form-group">
    <div class="col-sm-10">
      <%= f.collection_select(:course_term, @course_terms, :id, :to_s, {prompt: true}, {class: 'form-control'}) %>
    </div>
  </div>
  <%= f.submit 'Next', class: 'btn btn-primary' %>
<% end %>