config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :students
  resources :courses
  resources :course_terms

  get 'register', to: 'enrollments#select_term'
  post 'select_course', to: 'enrollments#select_course'
  post 'select_student', to: 'enrollments#select_student'
  post 'complete_registration', to: 'enrollments#complete_registration'

  root 'visitors#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :admin_only

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @enrollments_by_course_term = @course.enrollments.group_by(&:course_term)
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:number, :title, :description)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course, html: {class: 'form-horizontal'}) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :number, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :number, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', courses_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Courses</h2>

<table class="table">
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.number, course %></td>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td>
          <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, class: 'btn btn-default' %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @course %></h1>

<p>
  <%= @course.description %>
</p>

<% if !@enrollments_by_course_term.empty? %>
  <h2>Enrollments</h2>
  <% @enrollments_by_course_term.each do |course_term, enrollments| %>
    <h3><%= link_to course_term, course_term %></h3>
    <ul>
      <% enrollments.each do |enrollment| %>
        <li><%= link_to enrollment.student, enrollment.student %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_course_path(@course), class: 'btn btn-default'  %>
<%= link_to 'Back', courses_path, class: 'btn btn-default'  %>