config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :students
  resources :courses
  resources :course_terms

  get 'register', to: 'enrollments#select_term'
  post 'select_course', to: 'enrollments#select_course'
  post 'select_student', to: 'enrollments#select_student'
  post 'complete_registration', to: 'enrollments#complete_registration'

  root 'visitors#index'

end

app/models/course_term.rb
class CourseTerm < ActiveRecord::Base
  validates :year, :season, presence: true

  enum season: {winter: 0, spring: 1, summer: 2, fall: 3}

  def to_s
    "#{season.titleize} #{year}"
  end
end

app/controllers/course_terms_controller.rb
class CourseTermsController < ApplicationController
  before_action :set_course_term, only: [:show, :edit, :update, :destroy]
  before_action :admin_only

  # GET /course_terms
  # GET /course_terms.json
  def index
    @course_terms = CourseTerm.all
  end

  # GET /course_terms/1
  # GET /course_terms/1.json
  def show
  end

  # GET /course_terms/new
  def new
    @course_term = CourseTerm.new
  end

  # GET /course_terms/1/edit
  def edit
  end

  # POST /course_terms
  # POST /course_terms.json
  def create
    @course_term = CourseTerm.new(course_term_params)

    respond_to do |format|
      if @course_term.save
        format.html { redirect_to @course_term, notice: 'Course term was successfully created.' }
        format.json { render :show, status: :created, location: @course_term }
      else
        format.html { render :new }
        format.json { render json: @course_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_terms/1
  # PATCH/PUT /course_terms/1.json
  def update
    respond_to do |format|
      if @course_term.update(course_term_params)
        format.html { redirect_to @course_term, notice: 'Course term was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_term }
      else
        format.html { render :edit }
        format.json { render json: @course_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_terms/1
  # DELETE /course_terms/1.json
  def destroy
    @course_term.destroy
    respond_to do |format|
      format.html { redirect_to course_terms_url, notice: 'Course term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_term
      @course_term = CourseTerm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_term_params
      params.require(:course_term).permit(:season, :year)
    end
end

app/helpers/course_terms_helper.rb
module CourseTermsHelper
end

app/views/course_terms/_form.html.erb
<%= form_for(@course_term, html: {class: 'form-inline'}) do |f| %>
  <% if @course_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_term.errors.count, "error") %> prohibited this course_term from being saved:</h2>

      <ul>
        <% @course_term.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.select :season, CourseTerm.seasons.keys.to_a.map { |w| [w.humanize, w] }, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.text_field :year, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', course_terms_path, class: 'btn btn-default' %>
<% end %>

app/views/course_terms/edit.html.erb
<h1>Edit Course Term</h1>

<%= render 'form' %>

app/views/course_terms/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Course Terms</h2>

<table class="table">
  <thead>
    <tr>
      <th>Term</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @course_terms.each do |course_term| %>
      <tr>
        <td><%= link_to course_term, course_term %></td>
        <td>
          <%= link_to course_term, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course term', new_course_term_path, class: 'btn btn-default'  %>

app/views/course_terms/new.html.erb
<h1>New Course Term</h1>

<%= render 'form' %>

app/views/course_terms/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @course_term %></h2>

<%= link_to 'Edit', edit_course_term_path(@course_term), class: 'btn btn-default' %>
<%= link_to 'Back', course_terms_path, class: 'btn btn-default' %>