config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :students
  resources :courses
  resources :course_terms

  get 'register', to: 'enrollments#select_term'
  post 'select_course', to: 'enrollments#select_course'
  post 'select_student', to: 'enrollments#select_student'
  post 'complete_registration', to: 'enrollments#complete_registration'

  root 'visitors#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
      <p class="text-uppercase">Zion University</p>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if account_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            Welcome, <%= current_account.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Log out', destroy_account_session_path, method: 'delete' %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if account_signed_in? %>
<li><%= link_to 'Register', register_path %></li>
<% if current_account.admin? %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Create
    <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Course terms', course_terms_path %></li>
    <li><%= link_to 'Courses', courses_path %></li>
    <li><%= link_to 'Students', students_path %></li>
  </ul>
</li>
<% end %>
<% if current_account.student? %>
<li><%= link_to 'My courses', student_path(current_account.student) %></li>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zion University Online Course Registration</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
</body>
</html>